apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"certificates.k8s.io/v1","kind":"CertificateSigningRequest","metadata":{"annotations":{},"name":"vanj-csr"},"spec":{"expirationSeconds":86400,"request":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCk1JSUNWRENDQVR3Q0FRQXdEekVOTUFzR0ExVUVBd3dFZG1GdWFqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQNCmdnRVBBRENDQVFvQ2dnRUJBTTJFZG9zbXluUEJwNXVVZ2h0RkFJaVc3QnlOY1M1WG9FTXpJeWZLOWgreUhDNzMNCkZFWG92RHhTMEdlTEI0d0ZGR3JXd28ybEZzcmNHZlBCUHJHTy82ZXY2Tml6UUhUSGN4cjl3dllQNkNkL3p4a2INCmNBNERvMEZLQlFSUTRtU0lZaXJJdW00eHdtc3ZxNFpBOURodkFOWnpvY1Zna1pBbmJsQlRUL0liVHI4S0ZvVVQNCmNoWTdKdk9DRHVqVVVKSGlJTnVXRFhSWTE1bklqTUZoR2l5eDh5OFo1TDhhWElYUnZxTS83aXFsWkVqb0I4enQNCjlzRVhURFQ5anZidmUwOG1mRHJqUnB1VkFjU2Q0aFlSeWdubG42S05rSE9ZVjZZTjFtOFd2SFNJRnVyaXptYUINClJGM0Jkbm1VcStFc0Ewb0F3ZjFRUWtpbHdDTmRHSnBqL001RlNha0NBd0VBQWFBQU1BMEdDU3FHU0liM0RRRUINCkN3VUFBNElCQVFCNnNqVVpIM1lJTWRsMmVYdENNZzNiWURVd0N4Rm0vM3JkOHZiVEE0TGhmWmVzbUJ4ZGg0QjkNCklnVXVSd3R0NjQ1ZGN0ZTMvRjFxZUF2L0FwWEJqblpwT0ZxNlBCMU90NE1DeFhaZE1YeTF3WDQvNWJlaUl4VWwNCnNKa0NCWklObndhUlpmOFYyMVl5SXZCVlNIWXQ0WEJTN0E0N2poUFdBbjRyS3h3RnBRZUh6bFZlK2lqU3c5bVcNCk5NMG9ieGROYTlKNE4waFJwdHBud0d1QXR0VFhPdnJzQUpsZXhIaGk5b1MwaHFXdW43ZjFDRjM1R2VNRVdjcVUNCjQrczlLT21WNVZyc0ljamNKKytWd1BIZ3p3eWFGVk55WmxLUE5YRE5SNTZKYW5jdDh1ZFhVVEh3TXNJcDl2TTENCjVndW5WSElpWVcrVE1TVHg1bStxelZaenRPbDNNcGJrDQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCg==","signerName":"kubernetes.io/kube-apiserver-client","usages":["client auth"]}}
  creationTimestamp: "2025-12-30T15:44:18Z"
  name: vanj-csr
  resourceVersion: "64623"
  uid: 6109991e-0b4e-437e-a7d8-4bf551e42db1
spec:
  expirationSeconds: 8640000
  extra:
    authentication.kubernetes.io/credential-id:
    - X509SHA256=64c5a9fed6b11672e581a33a922d8a94bf97c930bd5cb2df1856db2fd166d803
  groups:
  - kubeadm:cluster-admins
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCk1JSUNWRENDQVR3Q0FRQXdEekVOTUFzR0ExVUVBd3dFZG1GdWFqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQNCmdnRVBBRENDQVFvQ2dnRUJBTTJFZG9zbXluUEJwNXVVZ2h0RkFJaVc3QnlOY1M1WG9FTXpJeWZLOWgreUhDNzMNCkZFWG92RHhTMEdlTEI0d0ZGR3JXd28ybEZzcmNHZlBCUHJHTy82ZXY2Tml6UUhUSGN4cjl3dllQNkNkL3p4a2INCmNBNERvMEZLQlFSUTRtU0lZaXJJdW00eHdtc3ZxNFpBOURodkFOWnpvY1Zna1pBbmJsQlRUL0liVHI4S0ZvVVQNCmNoWTdKdk9DRHVqVVVKSGlJTnVXRFhSWTE1bklqTUZoR2l5eDh5OFo1TDhhWElYUnZxTS83aXFsWkVqb0I4enQNCjlzRVhURFQ5anZidmUwOG1mRHJqUnB1VkFjU2Q0aFlSeWdubG42S05rSE9ZVjZZTjFtOFd2SFNJRnVyaXptYUINClJGM0Jkbm1VcStFc0Ewb0F3ZjFRUWtpbHdDTmRHSnBqL001RlNha0NBd0VBQWFBQU1BMEdDU3FHU0liM0RRRUINCkN3VUFBNElCQVFCNnNqVVpIM1lJTWRsMmVYdENNZzNiWURVd0N4Rm0vM3JkOHZiVEE0TGhmWmVzbUJ4ZGg0QjkNCklnVXVSd3R0NjQ1ZGN0ZTMvRjFxZUF2L0FwWEJqblpwT0ZxNlBCMU90NE1DeFhaZE1YeTF3WDQvNWJlaUl4VWwNCnNKa0NCWklObndhUlpmOFYyMVl5SXZCVlNIWXQ0WEJTN0E0N2poUFdBbjRyS3h3RnBRZUh6bFZlK2lqU3c5bVcNCk5NMG9ieGROYTlKNE4waFJwdHBud0d1QXR0VFhPdnJzQUpsZXhIaGk5b1MwaHFXdW43ZjFDRjM1R2VNRVdjcVUNCjQrczlLT21WNVZyc0ljamNKKytWd1BIZ3p3eWFGVk55WmxLUE5YRE5SNTZKYW5jdDh1ZFhVVEh3TXNJcDl2TTENCjVndW5WSElpWVcrVE1TVHg1bStxelZaenRPbDNNcGJrDQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
  username: kubernetes-admin
status:
  conditions:
  - lastTransitionTime: "2025-12-30T15:47:10Z"
    lastUpdateTime: "2025-12-30T15:47:10Z"
    message: This CSR was approved by kubectl certificate approve.
    reason: KubectlApprove
    status: "True"
    type: Approved
