apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-aff
  name: nginx-aff
spec:
  containers:
  - image: nginx
    name: nginx-affinity
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In 
            values:
            - hdd
status: {}
